CREATE USER 'WL'@'%' IDENTIFIED VIA mysql_native_password USING '***';GRANT ALL PRIVILEGES ON *.* TO 'WL'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

CREATE DATABASE 'WONDERLUST';
USE DATABASE 'WONDERLUST';

CREATE TABLE USERS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FULLNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(32) NOT NULL
);

CREATE TABLE BOOK(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL REFERENCES USERS(ID),
    FULLNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
    DESTINATION VARCHAR(20) NOT NULL,
    TRAVEL_DATE DATETIME NOT NULL,
    NUM_OF_TRAVELERS INT NOT NULL
);